language: node_js
sudo: false
node_js:
  - 'stable'
  - 10
cache:
  yarn: true
install:
  - yarn global add codecov
script:
  - yarn run lint
  - yarn run test-coverage
  - yarn run build
  - codecov
