language: node_js
sudo: false
node_js:
  - 'stable'
  - 10
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn global add codecov
script:
  - yarn lint
  - yarn test-coverage
  - codecov
  - yarn build